server:
  port: 18786

spring:
  application:
    name: service-feign
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    service-url:
#      defaultZone: http://root:root@localhost:18761/eureka/
      defaultZone: http://localhost:18761/eureka/

# feign自带断路器，但是默认是关闭的
feign:
  hystrix:
    enabled: true