server:
  port: 18762

spring:
  application:
    name: service-test
    # 默认值
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      # Sleuth 默认采样算法的实现是 Reservoir sampling，具体的实现类是 PercentageBasedSampler，
      # 默认的采样比例为: 0.1，即 10%。我们可以通过 spring.sleuth.sampler.probability 来设置，
      # 所设置的值介于 0 到 1 之间，1 则表示全部采集
      probability: 1.0

eureka:
  client:
    service-url:
#      defaultZone: http://root:root@localhost:18761/eureka/
      defaultZone: http://peer1:18760/eureka/,http://peer2:18761/eureka/
  instance:
    # 不想使用主机名进行访问注册中心，也可以使用ip，但是需要先添加一条配置，该值默认false
    prefer-ip-address: true
debug: true