server:
  port: 18762

spring:
  application:
    name: service-test
    # 默认值
#  zipkin:
#    base-url: http://localhost:9411

eureka:
  client:
    service-url:
#      defaultZone: http://root:root@localhost:18761/eureka/
      defaultZone: http://localhost:18761/eureka/