server:
  port: 9411

spring:
  application:
    name: service-zipkin

eureka:
  client:
    service-url:
#      defaultZone: http://root:root@localhost:18761/eureka/
      defaultZone: http://localhost:18761/eureka/