server:
  port: 18766

spring:
  application:
    name: service-ribbon
  zipkin:
      base-url: http://localhost:9411

eureka:
  client:
    service-url:
      defaultZone: http://root:root@localhost:18761/eureka/
